[package]
name = "earth-rotation"
version = "0.1.0"
authors = ["ChatGPT <your.email@example.com>"]
edition = "2018"



# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glutin = "0.26.0"
gl = "0.14.0"
cgmath = "0.17.0"
image = "0.23.12"